### PR TITLE
Fix checking of scrollTo()

### PR DESCRIPTION
**Pull request by zvona**
This error occurs with Jest and tests won't pass.

### CODE REVIEW

**Comment by satya164** [comment]
Can you file a bug report in React Native's repo? This is a bug in jest's React Native preset. I don't want to add this check because it just suppresses the issue. The tests should behave the same as actual code.

**Comment by zvona** [comment]
Ok, thanks for reply. I examined a little and this really is a generic issue on Jest. Both ListView and ScrollView needs to be mocked in order to run the tests properly.

https://github.com/facebook/react-native/issues/11659#issuecomment-282448969

**Comment by alvaromb** [comment]
I've just opened a bug in the `react-native` repo https://github.com/facebook/react-native/issues/13034

**Comment by alvaromb** [comment]
PR: https://github.com/facebook/react-native/pull/13048

**Pull request closed without merging**
