### PR TITLE
Fix tabBarVisible on android device.

### PR DESCRIPTION
**Pull request by mindk**
Fix bug with blank screen on android device when set  tabBarVisible = true.

### CODE REVIEW

**Comment by jsierles** [comment]
Why is this opacity value required for Android?

**Comment by satya164** [comment]
Why does this work? Do you have link to an issue in RN repo?

**Comment by mindk** [comment]
Android can't rerender screen with animation if we remove one of elements before content (like a top bar container). But it works correctly if we change dimensions of this elements. So I wrapped topBar into View element. View with style {opacity: 1} works as separately container, but  if remove this style than we will have same bug again.

**Comment by satya164** [comment]
Not sure what you mean by that. The disappearing screen bug seems to be caused by buggy zIndex implementation on Android (https://github.com/react-native-community/react-native-tab-view#tabbar-disappears-or-shows-weird-behaviour-when-conditionally-rendering-items).

Your PR seems to fix that, because `opacity: 1` implicitly sets the wrapper view to be non-collapsable on Android, and the wrapper `View` means that the tabbar is no longer the sibling of the view, which results in the z-Index related bug not appearing.

I just pushed a commit which explictly sets `collapsable` to `false`, which should fix the issue -
 c80fdff7bdb59b281c324bb6fb0dd1f213c1aae6

**Pull request closed without merging**
