### PR TITLE
Example for dynamic tab load

### PR DESCRIPTION
**Pull request by spezzino**

### CODE REVIEW

**Comment by karanjthakkar** [comment]
@spezzino I was looking into #130 to understand the motivation behind this PR. I think the way your example portrays dynamic tab loading is essentially just showing a loading indicator and then rendering the actual TabView. Personally, this doesn't seem to be a solution specific to this library but just how you load any component that depends on some data that may be available in the future. That being said, I'll leave it to @satya164 to see if he believes this might add value. Thanks for your effort!

**Comment by spezzino** [comment]
It is just an example to help people looking into this solution

**Comment by satya164** [comment]
I'll add a better example soon.

**Comment by dsp1589** [comment]
@satya164 did you create better example? It re-renders all the tabs. one of the tab contains webview which is reloading every time we add a tab.

**Comment by khat33b** [comment]
I tried running this example. I am getting this error:
```
Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Pull request closed without merging**
