### PR TITLE
WIP: Dynamic width in TabBar

### PR DESCRIPTION
**Pull request by jaitd**
### Motivation

We use `react-native-tab-view` to show a swipeable menu for restaurants. The problem that we face is that the section names in the `TabBar` can be of varying length along with the fact that the `TabBar` needs to be scrollable. We found this RFC for Dynamic tab width in PR #356 but it hasn't seen updates for a while. We are already using the implementation from this pull request in our production app and haven't heard any complaints except the issue mentioned below.

### Implementation

In this pull request, we present our implementation to enable dynamic tab width in the `TabBar`. The feature can be enabled by setting the `dynamicWidth` prop for `TabBar`. 

`TabBar` listens to `onLayout` events for `View` components for a tab to find out the width of tab on the screen. These widths are stored in a map, which is in turn used to perform all the calculations for animations. We animate both the x-movement as well as the width of the indicator which leads to a nice visual effect.

### Remaining Issue

Currently, the `TabBar` scroll position is not kept in sync with the pan position received from the pager. We experimented with different pagers but in all cases the performance takes a large hit and the animation becomes very choppy. Our guess is that, the pan listener is fired a lot of times while panning on the pager which in turn leads to a lot of `scrollTo` calls on the `ScrollView`. @satya164, would you have any suggestions to improve this?

### Test plan

The example folder has been updated to include a page which showcases this feature. You can see it in action on Snack: [link](https://snack.expo.io/@jaitdixit/github.com-orda-technologies-react-native-tab-view:example@develop). Let me know if you want anything tested more specifically.

### CODE REVIEW

**Comment by erickreutz** [comment]
It's quite unfortunate that a PR like this doesn't even get a comment from maintainers. @jaitd is this the solution you ended up going with?

**Comment by PierreCapo** [comment]
Any news about this PR @jaitd ? It would be a really useful addition to the lib.

**Comment by andrictham** [comment]
Any updates on this?

**Comment by jaitd** [comment]
Apologies for the late reply.

@erickreutz This is the solution that we went for in our app. Except for the issues mentioned in the pull request, we have not encountered any major problems.

@PierreCapo @andrictham I'm still waiting to hear from @satya164.

**Comment by nehacurefit** [comment]
What is the plan for merging this PR? This is really great and useful

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. It's gone through a major refactor and there will be conflicts with your PR.

Please try the new version and see if it addresses your issue. If not, please open a new PR with the change.

**Pull request closed without merging**
