### PR TITLE
test: setup detox

### LINKED ISSUE #469: Setup infra for testing with detox

### PR DESCRIPTION
**Pull request by chakrihacker**
closes #469

### Motivation
Setup Infra for testing

### Test plan

- [x] Detox Android
- [x] Detox ios

### CODE REVIEW

**Comment by chakrihacker** [comment]
Hi, I am trying to use https://github.com/react-native-community/react-native-circleci-orb for **circleci** setup. If I can have access for it, I will try to set up or else I will remove the last commit and we can try another PR for circleci

**Comment by chakrihacker** [comment]
Any update on this??

**Comment by osdnk** [comment]
Hi, @chakrihacker 
What do you want us to do?

**Comment by chakrihacker** [comment]
I am getting this error when using orbs
`Orb react-native-community/react-native@1.2.0 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.`

please enable use of third party orbs

**Comment by satya164** [comment]
hey @chakrihacker, it's already enabled in circleci settings. maybe it's because the branch is under your personal user? I just gave you write access to this repo so you can try by creating a branch.

**Comment by chakrihacker** [comment]
Thanks for access, I will finish this weekend

**Comment by chakrihacker** [comment]
I think it's time to request mac plan.
More details here https://circleci.com/open-source/
need to put a mail to circleci team

**Comment by satya164** [comment]
Thanks! I'll check it.

**Comment by osdnk** [comment]
@chakrihacker @satya164 
Maybe we can use Travis for it?

**Comment by satya164** [comment]
Whichever is easier :)

**Comment by chakrihacker** [comment]
Travis ci doesn't support orbs

**Comment by osdnk** [comment]
We'll contact circleCI for it! We do also want to use it bc Travis does not support Android virtualization well.

**Comment by satya164** [comment]
@chakrihacker I emailed circleci and we already have a Mac OS plan active for the community org. Can you move this branch to the repo so we can check if the tests run?

**Comment by chakrihacker** [comment]
ok

**Pull request closed without merging**
