### PR TITLE
feat: Add method argument to onIndexChange callback

### PR DESCRIPTION
**Pull request by Jyrno42**
This argument is either gesture/tap and allows one to differentiate between the action user took to change the active scene.

### Motivation

In the app I am building, I need to track the change method for analytics.

### Test plan

Verified manually that this change did not cause any regressions.

### CODE REVIEW

**Comment by Jyrno42** [comment]
Rebased on top of the TS conversion.

**Comment by satya164** [comment]
I'm not sure about this. `jumpToIndex` being called doesn't mean it's a tab press.

> In the app I am building, I need to track the change method for analytics.

You can use the `onTabPress` callback to check tab changes due to tab press.

**Comment by Jyrno42** [comment]
> I'm not sure about this. `jumpToIndex` being called doesn't mean it's a tab press.

Did you mean to write `jumpTo`? Since in the PR `jumpToIndex` of TabView only forwards the passed argument.

Using onTabPress requires me to use an instance variable to prevent sending a second analytics event from `onIndexChange` callback.

**Comment by Jyrno42** [comment]
What if I change the implementation like this:

1. Add second argument to Pager.jumpTo and pass it along to calls to `this.props.onIndexChange` in its body.
2. Modify `onPress` handler of `TabBarItem` inside `TabBar.tsx` to and add a second argument 'tap' to `this.props.jumpTo` call
3. [Optional] Change constant string 'gesture' to 'other' for semantic reasons (it might be a gesture or a reaction to a changed index in props)

**Comment by satya164** [comment]
I need to think about it a bit.

> Using onTabPress requires me to use an instance variable to prevent sending a second analytics event from onIndexChange callback which is not very elegant.

For now this seems reasonable. We do similar in react-navigation.

**Comment by Jyrno42** [comment]
Used `onTabPress` and got the functionality I wanted.

this PR can be closed from my perspective

**Pull request closed without merging**
