### PR TITLE
Added optional swipeEnabled prop to TabViewAnimated.

### PR DESCRIPTION
**Pull request by alvaromb**
You can disable the automatic swipe for a `TabViewAnimated` component.

### CODE REVIEW

**Comment by knowbody** [comment]
I don't think there is a point for having it as you can already accomplish it via `renderPager`, see NoAnimation exmaple

**Comment by alvaromb** [comment]
Mmm, you're right @knowbody. Just thought it was handy.

**Comment by alvaromb** [comment]
Thanks for your feedback Mateusz! 🙇

**Comment by knowbody** [comment]
no, thanks for your PR! I think you can leave it open and see what @satya164 has to say, I was actually using that yesterday, the first thing I did was to add `swipeEnabled` on `TabViewAnimated`, but then @satya164 told me about `renderPager`. So it would just be a duplication, I think

**Comment by alvaromb** [comment]
I think is better to discard this PR, you're right it makes no sense because you can set the pager through `renderPager`. However, maybe it's interesting to stick an small example into the docs. I will be more than happy to provide a snippet if you guys find it's useful.

BTW, great component!

**Comment by knowbody** [comment]
Definitely useful to document it! mind sending a PR?

**Comment by satya164** [comment]
Thanks a lot for the PR. I think `swipeEnabled` on `TabViewAnimated` is a better API, but since we support swappable pagers, it's not really the correct thing to do. Since the underlying pagers could accept different props (for example, `TabViewPagerPan` accepts 2 extra props), and it might not have a `swipeEnabled` prop at all depending on the implementation. I guess it's just maintaining a balance between customisability and simplicity.

About docs, I think we can have a FAQ section outlining common things like this. Help is appreciated :)

**Comment by alvaromb** [comment]
Ok! I'm in the middle of something, I'll send a PR with a FAQ proposal later today.

**Pull request closed without merging**
