### PR TITLE
feat: add dynamic tab width support

### PR DESCRIPTION
**Pull request by Taylor123**
### Motivation

There is currently no support for tabs that have a variable width. This is a common design and seems to be something the community wants  (https://github.com/react-native-community/react-native-tab-view/issues/356).

Credit to @jaitd for the initial related PR (https://github.com/react-native-community/react-native-tab-view/pull/544)

### Test plan

Checked with the example app and tested on my production app. I can publish it to npm to create a snack if it's necessary.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks a lot for the PR. I'll check soon.

**Comment by Taylor123** [comment]
@satya164 found a bug that i need to work through. When on the last page of a scrollable tab, a swipe gesture from right to left will scroll the tab back to the beginning. Will try to get an update for this asap

**Comment by salhotra** [comment]
@satya164 Could you take a look at @Taylor123 's PR please? This will help me in my use case as well, like many others I suppose. Thanks

**Comment by satya164** [comment]
I ran this locally and seems to work great. There is a minor during startup, on Android, the indicator is not on correct position until you touch the screen, on iOS, the indicator starts at the wrong position and then snaps to the correct position.

**Comment by Taylor123** [comment]
> I ran this locally and seems to work great. There is a minor during startup, on Android, the indicator is not on correct position until you touch the screen, on iOS, the indicator starts at the wrong position and then snaps to the correct position.

This most likely happens because all the tabs need to be measured before the indicator can be scaled and translated properly. I'll look into improving that when I get some free time

**Comment by jamiepine** [comment]
would it hurt to merge it despite the slight android startup bug? I would really benefit from using this in my project.

**Comment by satya164** [comment]
I don't want to merge a feature with noticeable glitch on every mount. You can temporarily fork the branch and use it instead, you don't have to wait for a release.

**Comment by Taylor123** [comment]
Sorry been swamped and haven't had time to look into this further since it hasn't been a priority. Will see if i can find some time this week or weekend

**Comment by Taylor123** [comment]
I've rebased on top of master (finally), but there are still issues with android. The `onLayout` callbacks take too long, few hundred ms at worst for some of the `tabBarItems`, which is why the indicator and scroll position is janky on mount for android. iOS seems much faster, so the dynamic measurements aren't noticeable.

I don't have too much time these days to contribute to this library since I've shifted away from using it, so if anyone wants to fork this and continue or discuss, happy to chat through it

**Comment by satya164** [comment]
Thank you @Taylor123. I'll tweet this so maybe someone will have time to look into this.

I think to address issues with `onLayout` firing too late, we could do something like hide the indicator by default, wait for it to fire for tabs till the active tab and then fade it in since it's enough for us to calculate the position.

Hopefully this situation will be better once Fabric lands in React Native.

**Comment by ankeetmaini** [comment]
I can take a look this weekend!

**Comment by vikramkh** [comment]
How exactly do I use this? Sorry very new to this.

**Comment by Taylor123** [comment]
@vikramkh run `yarn add Taylor123/react-native-tab-view#feature/dynamic-tab-width` instead of `yarn add react-native-tab-view`

Or you can fork my branch and use your fork as a dependency for your project (this way you can rebase on top of master if my branch gets too behind)

**Comment by vikramkh** [comment]
Thanks so much for responding! If I fork it, how do I add it to my project? Just copy and paste it into node modules, and then if it gets behind, I import from the master instead?

**Comment by Taylor123** [comment]
@vikramkh Don't copy and paste. If you fork it, use your forked repository as the source of truth. NPM supports github urls, so fill in `yarn add [GITHUB_USERNAME]/[REPO_NAME]#[BRANCH_NAME]` with the necessary details and it will pull the contents from the repo into your project. If you're using the master branch, skip the `#[BRANCH_NAME]`

**Comment by vinicarra** [comment]
We definitely need this to be merged in master! This is a common requirement for many use cases, especially if using dynamic tabs!

**Comment by RPlaha0390** [comment]
Hi @Taylor123, I too am having the same issue with the `auto` width.  I tried to fork the branched version of this library but when I run my the app I receive this error: 
```While trying to resolve module `react-native-tab-view` from file `path-to-app/src/components/Tabs/Tabs.tsx`, the package `path-to-app/node_modules/react-native-tab-view/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (path-to-app/node_modules/react-native-tab-view/lib/module/index.js`.```

`lib/module/index.js` files are missing it seems. 

It would be really useful if we can get this auto width fixed. Appreciate you've shifted away from using it though.

**Comment by satya164** [comment]
Closing in favor of #823

**Comment by vikramkh** [comment]
@satya164 Sorry I'm quite new, does this mean that, according to #823, the auto works now.  And if so, will it be fix merged to the master then?

**Comment by satya164** [comment]
It's a continuation of this PR. It'll be merged to master when the review comments are addressed and I've tested it.

**Comment by jesster2k10** [comment]
> Hi @Taylor123, I too am having the same issue with the `auto` width. I tried to fork the branched version of this library but when I run my the app I receive this error:
> `` While trying to resolve module `react-native-tab-view` from file `path-to-app/src/components/Tabs/Tabs.tsx`, the package `path-to-app/node_modules/react-native-tab-view/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (path-to-app/node_modules/react-native-tab-view/lib/module/index.js`. ``
> 
> `lib/module/index.js` files are missing it seems.
> 
> It would be really useful if we can get this auto width fixed. Appreciate you've shifted away from using it though.

I hade the same issue too

**Comment by rochapablo** [comment]
I have just tried the new version `width: 'auto'`, but the indicator don't have the same size. Am I missing something?

```
"react": "16.8.6",
"react-native": "^0.59.10",
"react-native-tab-view": "^2.8.0",
```

**Comment by ankeetmaini** [comment]
Giving 'auto' means the indicator width is dynamic depending upon the
header content.

**Comment by LaszloDev** [comment]
Is there a way for the tabs to have `width: auto` but on the same time not aligned to the left? I would like to have them evenly across the width of the tabbar, but each with its width based on the tab-label content.
My idea would be to give the parent view `justifyContent: 'space-around'`.

**Pull request closed without merging**
