### PR TITLE
feat: add InteractionHandle

### LINKED ISSUE #903: Integrate with InteractionManager
By default, reanimated and gesture handler don't integrate with `InteractionManager`. We should do the integration in this library.

### How?

We need to create an interaction handle when a swipe gesture starts or animation stats. To create a handle:

```js
this.interactionHandle = InteractionManager.createInteractionHandle()
```

Then clear this handle when swipe gesture ends, animation ends or component unmounts.

```js
InteractionManager.clearInteractionHandle(this.interactionHandle)
```

### PR DESCRIPTION
**Pull request by Naturalclar**
This PR fixes #903 
### Motivation

This PR integrates InteractionManager with TabView Pager

### Test plan

yarn 
yarn lint
yarn test

### CODE REVIEW

**Comment by osdnk** [comment]
Hey, @Naturalclar 
Can you explain do we really need this?

/@janicduplessiss

**Comment by janicduplessis** [comment]
This will prevent things that use InteractionManager from doing expensive work during transitions. An example is FlatList that doesn't render new rows during interactions.

**Comment by Naturalclar** [comment]
@osdnk Sorry for the late response!
as @janicduplessis mentioned, this PR's intention is to setup InteractionManager to prevent heavy loads during transitions.
Since react-native-reanimated and react-native-gesture-handler doesn't integrate with InteractionManager, it would be nice to have the handler in this package.

**Comment by osdnk** [comment]
Sorry for the late answer. I'd love to merge it/
Can you resolve conflicts?

**Comment by Naturalclar** [comment]
@osdnk I've resolved the conflict and squashed commits. :)

**Comment by osdnk** [comment]
One more thing! Can you add it also to the`ScrollPager.tsx`?

**Comment by Naturalclar** [comment]
@osdnk Done!

**Comment by osdnk** [comment]
Thanks

**Pull request merged**
