### PR TITLE
Feature/detox setup

### PR DESCRIPTION
**Pull request by chakrihacker**

### CODE REVIEW

**Comment by chakrihacker** [comment]
We can merge this to master

**Comment by osdnk** [comment]
@satya164 please take a look

**Comment by osdnk** [comment]
mmmm can I help this PR somehow?

**Comment by osdnk** [comment]
I'm not sure if I want to use circleCI. It costs money, this project is totally free so here's a conflict. Can't we have only Travis setup for things like typechecks, unit tests etc.
I'm afraid I cannot accept detox tests until figuring out something about funding / switching to free Travis.

**Comment by chakrihacker** [comment]
Hey @osdnk CircleCI provides free minutes for opensource

**Comment by osdnk** [comment]
yeah, but it's not sufficient, no?

**Comment by chakrihacker** [comment]
Based on this link https://circleci.com/pricing/#faq-section-os-x
repo will have 1x concurrency mac os worth $2400. Do we use more than that??

**Pull request closed without merging**
