### PR TITLE
Feature/detox setup

### PR DESCRIPTION
**Pull request by chakrihacker**

### CODE REVIEW

**Comment by chakrihacker** [comment]
@osdnk @satya164 can you trigger a build from community??

**Comment by satya164** [comment]
Not sure why the build is not triggering. I invited you to the community org, can you accept it?

**Comment by chakrihacker** [comment]
Hi, Thanks for inviting to the community. 
I took a macos trial plan and now I am able to run ios builds with detox. But for Android, there's some issue testing E2E. even in my local when I build 2nd time tests are running. I have to dig deeper into that

**Comment by chakrihacker** [comment]
Hi, can we just run detox tests for ios now, I will make another PR for android detox

**Comment by satya164** [comment]
@chakrihacker yea sounds good. I don't wanna merge the PR into master yet as I wanna setup expo bare workflow too. So let's keep this branch under `develop`

**Comment by chakrihacker** [comment]
I pushed a develop branch with same commits

**Pull request closed without merging**
