### PR TITLE
Added a upperCase property

### PR DESCRIPTION
**Pull request by mahomahoxd**
Instead of always having uppercase titles, by default there is no uppercase only if you pass the uppercase property.

### CODE REVIEW

**Comment by satya164** [comment]
You can use the `getLabel` prop like `getLabel = ({ route }) => route.title`

**Comment by mahomahoxd** [comment]
There is no such thing as getLabel in the properties that I have. I don't see any kind of properties or a way to set it without the uppercase (Without the use of a custom component of some sort). If you find me an alternative, sure. Otherwise I don't see a reason for not putting it in such a way like I already did.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#tabbar-

**Comment by wahidin32** [comment]
thats {{ route }} means, point to the array from the tab?

state = {
    index: 0,
    routes: [
      //key & title dari tabnya...
      { key: '1', title: '1' },
      { key: '2', title: '2' },
      { key: '3', title: '3' },
      { key: '4', title: '4' },
      { key: '5', title: '5' },
    ],
  };

**Pull request closed without merging**
